import Image from "next/image";
import { AvisInteractive, CertificateGallery, Header, ModeTabs, PocGallery, ReferenceExplorer, RevealController } from "@/components/client";
import { Arrow, Brain, Chart, Database, Eye, Factory, Layers, Mail, Mic, Phone, Pin, Qr, Robot, Spark, Tool } from "@/components/icons";
import { achievements, contact, cycle, screens, timeline } from "@/lib/data";

function Heading({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="section-head"><p>{eyebrow}</p><h2>{title}</h2><span>{copy}</span></div>}

export default function Page(){return <>
  <RevealController/><Header/>
  <main id="top">
    <section className="hero">
      <div className="wide hero-grid">
        <div className="hero-copy"><p className="hero-kicker"><i/>Manufacturing AI, in operation</p><h1>AI that works where manufacturing decisions happen.</h1><p className="hero-lead">DX Solutions connects shop-floor signals, enterprise data, vision intelligence, and AI agents—turning operational context into faster, clearer action.</p><div className="hero-actions"><a className="btn primary" href="#mode">Explore our solutions <Arrow/></a><a className="btn ghost" href="#references">View AI references</a></div><div className="hero-chips"><span>Physical AI</span><span>AI Agents</span><span>Vision Intelligence</span></div></div>
        <div className="hero-visual"><div className="hero-image"><Image src="/media/hero/factory.webp" alt="Automated manufacturing environment" fill priority sizes="(max-width:900px) 100vw, 56vw"/><i/><b/></div><div className="float-card top"><span className="live"/><div><small>Unified context</small><strong>Factory + Office</strong></div></div><div className="float-card bottom"><span className="agent"><Brain/></span><div><small>Decision layer</small><strong>Agent-ready</strong></div></div></div>
      </div>
      <div className="wide hero-stats" data-reveal><div><strong>28</strong><span>AI project references</span></div><div><strong>10</strong><span>IP & certification records</span></div><div><strong>04</strong><span>Connected AI domains</span></div><div className="scroll-hint"><i/>Scroll to explore</div></div>
    </section>

    <section id="company" className="section company"><div className="shell">
      <Heading eyebrow="01 — Company" title="Tomorrow’s technology, engineered for today’s factory." copy="DX Solutions has progressed from rule-based automation to physical AI and manufacturing agents—always anchored in deployable, field-ready outcomes."/>
      <div className="intro" data-reveal><div className="quote"><span>“</span><p>We research the technology of tomorrow—and make it useful inside real operations today.</p></div><div className="principles"><article><i><Factory/></i><div><h3>Field-first</h3><p>Built around actual manufacturing constraints, workflows, and users.</p></div></article><article><i><Database/></i><div><h3>Context-connected</h3><p>Combines equipment, process, vision, and enterprise information.</p></div></article><article><i><Robot/></i><div><h3>Action-oriented</h3><p>Moves beyond dashboards into guidance, automation, and agent execution.</p></div></article></div></div>
      <div className="timeline-block" data-reveal><div className="subhead"><div><p className="eyebrow">Technology evolution</p><h3>From rules to agents.</h3></div><p>Six years of capability building across manufacturing AI.</p></div><div className="timeline">{timeline.map((x,i)=><article key={x.year}><div><b>{x.year}</b><span>0{i+1}</span></div><h4>{x.title}</h4><p>{x.copy}</p><footer>{x.tags.map(t=><span key={t}>{t}</span>)}</footer></article>)}</div></div>
      <div className="achievement" data-reveal><div className="subhead"><div><p className="eyebrow">Recognition</p><h3>Selected achievements</h3></div><p>Field results recognized across public, industrial, and innovation programs.</p></div><div className="achievement-track">{achievements.map(x=><article key={x.title}><div><Image src={x.image} alt="" fill sizes="(max-width:650px) 82vw, 380px"/></div><footer><span>{x.year}</span><h4>{x.title}</h4></footer></article>)}</div></div>
      <PocGallery/><CertificateGallery/>
    </div></section>

    <section id="mode" className="section mode"><div className="shell">
      <Heading eyebrow="02 — Solution 1" title="M.O.D.E. unifies manufacturing and office decisions." copy="Manufacturing & Office Decision Engine connects operational infrastructure, specialized AI, and agent workflows through one integrated control platform."/>
      <div className="architecture" data-reveal><div className="arch-copy"><p className="eyebrow">Integrated architecture</p><h3>One operating layer, four levels of intelligence.</h3><p>M.O.D.E. organizes fragmented factory and office systems into a clear stack—from existing infrastructure to agent-led action.</p><div><span><Eye/>Vision sensors</span><span><Tool/>Equipment signals</span><span><Database/>ERP · MES · SCM</span><span><Mic/>Smart glasses</span></div></div><div className="stack"><article className="red"><b>L04</b><i><Spark/></i><div><h4>AI Agent</h4><p>Context-aware decisions, guidance, and workflow execution</p></div></article><article><b>L03</b><i><Brain/></i><div><h4>AI-based Intelligence</h4><p>Materials, production, equipment, quality, and office AI</p></div></article><article><b>L02</b><i><Database/></i><div><h4>Operational Infrastructure</h4><p>Vision, sensors, automation, ERP, MES, and SCM</p></div></article><article><b>L01</b><i><Layers/></i><div><h4>Unified Platform</h4><p>A shared control layer across factory and office operations</p></div></article><footer><Image src="/media/brand/logo.png" alt="DX Solutions" width={718} height={174}/><span>AI Integrated Control Platform</span></footer></div></div>
      <ModeTabs/>
      <div className="screen-gallery" data-reveal><div className="subhead"><div><p className="eyebrow">One platform, multiple views</p><h3>Use the interface each decision requires.</h3></div><p>Planning, quality, inspection, and digital-twin views share a common operational context.</p></div><div>{screens.map(([name,label])=><figure key={name}><span><Image src={`/media/platform/${name}.webp`} alt={label} fill sizes="(max-width:650px) 84vw, 430px"/></span><figcaption>{label}</figcaption></figure>)}</div></div>
    </div></section>

    <section id="avis" className="section avis"><div className="shell">
      <Heading eyebrow="03 — Solution 2" title="A.V.I.S. brings the manufacturing agent to the worker." copy="A.V.I.S. uses equipment data, MES context, on-device small language models, voice, vision, and wearables to provide the right answer at the point of work."/>
      <div className="lookup" data-reveal><div className="lookup-copy"><p className="eyebrow">Context at the point of work</p><h3>Identify, inspect, and understand—without breaking the workflow.</h3><p>A tablet or wearable interface retrieves the correct equipment history, manual, and action context when it is needed most.</p><div><span><Qr/>Scan</span><i/><span><Brain/>Understand</span><i/><span><Spark/>Guide</span></div></div><div className="lookup-cards"><article><div><Image src="/media/avis/equipment-lookup.webp" alt="Equipment identification interface" fill sizes="260px"/></div><footer><Eye/><h4>Equipment identification</h4><p>Recognize equipment context and retrieve inspection history in the field.</p></footer></article><article><div><Image src="/media/avis/history-detail.webp" alt="Detailed history interface" fill sizes="260px"/></div><footer><Database/><h4>Detailed history</h4><p>Review previous actions, results, and records without returning to a desk.</p></footer></article><article><div className="wide-img"><Image src="/media/avis/qr-lookup.webp" alt="QR manual lookup" fill sizes="260px"/></div><footer><Qr/><h4>QR and manual access</h4><p>Open the right manual immediately through QR context and guided search.</p></footer></article></div></div>
      <AvisInteractive/>
      <div className="cycle" data-reveal><div className="cycle-head"><div><i><Chart/></i><div><p className="eyebrow">AI agent analysis</p><h3>Locate the process that sets the line’s pace.</h3></div></div><aside><span>UPPH</span><strong>3.20 → 4.16</strong><b>+30% target</b></aside></div><div className="bars"><div className="target"><span>Target 13.3 sec</span></div>{cycle.map(([name,value])=><article key={name}><div><span className={value>13.3?"over":""} style={{height:`${value/22.2*100}%`}}><b>{value.toFixed(1)}</b></span></div><p>{name}</p></article>)}</div><small>Average cycle-time values from the production-line analysis. Processes above the 13.3-second target are highlighted.</small></div>
    </div></section>

    <section id="references" className="section references"><div className="shell"><div className="ref-title"><Heading eyebrow="AI References" title="A track record across the manufacturing value chain." copy="Explore selected development work spanning predictive maintenance, process optimization, vision inspection, office intelligence, physical AI, and robotics automation."/><aside><strong>28</strong><span>selected<br/>projects</span></aside></div><ReferenceExplorer/></div></section>

    <section id="contact" className="contact"><div className="contact-grid-bg"/><div className="shell"><div className="contact-lead" data-reveal><p>Start with the operational challenge.</p><h2>Build the next manufacturing standard with DX Solutions.</h2><a href={`mailto:${contact.email}`}>{contact.email}<Arrow size={28}/></a></div><div className="contact-cards" data-reveal><article><i><Mail/></i><div><span>Email</span><a href={`mailto:${contact.email}`}>{contact.email}</a></div></article><article><i><Phone/></i><div><span>Phone</span><a href={`tel:${contact.tel}`}>{contact.phone}</a></div></article><article><i><Pin/></i><div><span>Headquarters</span><address>{contact.hq}</address></div></article><article><i><Pin/></i><div><span>Branch & R&amp;D Center</span><address>{contact.branch}</address></div></article></div><footer className="footer"><a href="#top"><Image src="/media/brand/logo.png" alt="DX Solutions" width={718} height={174}/></a><p>Manufacturing AI in operation.</p><a href={contact.website} target="_blank" rel="noreferrer">Corporate website <Arrow size={14}/></a></footer></div></section>
  </main>
</>}
